---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Iniciar servicio 
      ansible.builtin.service:
        name: nginx
        state: started
      register: nginx
  

    - name: Comprobar servicio
      ansible.builtin.assert:
        that: not nginx.changed
        success_msg: "nginx corriendo"
        fail_msg: "error con servicio nginx"


    - name: Comprobar conexion a proxy para comprobar redireccion
      ansible.builtin.uri:
        url: http://localhost/
      register: pagina


    - name: Comprobar codigo http
      ansible.builtin.assert:
        that: pagina.status == 200
        success_msg: "Conexion correcta a pagina "
        fail_msg: "Conexion incorrecta ({{ pagina.status }})"

...